# Generated by Django 4.2.20 on 2025-09-30 04:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Announcement Content'),
        ),
    ]
