# Generated by Django 4.2.20 on 2025-05-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
