# Generated by Django 4.2.20 on 2025-05-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='events',
            name='registration_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='events',
            name='sec_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('WNCXP', 'WNCXP - Wednesday Night Cyclocross Practice'), ('Women+Clinic', 'Women+ (FWTNB) Clinic'), ('LMCX', 'Lower Mainland Cyclocross Race'), ('KinderCross', 'KinderCross - Kids Cyclocross')], default='LMCX', max_length=50),
        ),
    ]
