# Generated by Django 4.2.20 on 2025-06-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_main_image_events_registration_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('WNCXP', 'WNCXP - Wednesday Night Cyclocross Practice'), ('Clinic', 'Women+ (FWTNB) Clinic'), ('Races', 'Lower Mainland Cyclocross Race'), ('KiddieCross', 'KiddieCross - Kids Cyclocross')], default='Races', max_length=50),
        ),
    ]
