# Generated by Django 4.2.20 on 2025-06-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_events_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='sec_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('wncxp', 'WNCXP - Wednesday Night Cyclocross Practice'), ('clinic', 'Women+ (FWTNB) Clinic'), ('races', 'Lower Mainland Cyclocross Race'), ('kiddiecross', 'KiddieCross - Kids Cyclocross')], default='races', max_length=50),
        ),
    ]
