# Generated by Django 4.2.20 on 2025-07-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_events_main_image_alter_events_sec_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/events'),
        ),
        migrations.AlterField(
            model_name='events',
            name='sec_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/events'),
        ),
    ]
