# Generated by Django 4.2.20 on 2025-07-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_events_main_image_alter_events_sec_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='events',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/events', verbose_name='Main Event Image'),
        ),
        migrations.AlterField(
            model_name='events',
            name='sec_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/events', verbose_name='Icon Image'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('wncxp', 'WNCXP - Wednesday Night Cyclocross Practice'), ('clinic', 'Women+ (FWTNB) Clinic'), ('races', 'Lower Mainland Cyclocross Race'), ('kiddiecross', 'KiddieCross - Kids Cyclocross')], default='races', max_length=50, verbose_name='Event Type'),
        ),
    ]
