# Generated by Django 4.2.20 on 2025-08-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_events_options_alter_events_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('wncxp', 'WNCXP - Wednesday Night Cyclocross Practice'), ('clinic', 'Women+ (FWTNB) Clinic'), ('races', 'Lower Mainland Cyclocross Race'), ('kindercross', 'KinderCross - Kids Cyclocross')], default='races', max_length=50, verbose_name='Event Type'),
        ),
    ]
