# Generated by Django 4.2.20 on 2025-09-30 04:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_events_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Event Description'),
        ),
    ]
