# Generated by Django 4.2.20 on 2026-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_events_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
